### ISSUE TITLE
Run Travis for fenics-adapter tests

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/fenics-adapter#24]
Using the command `python setup.py test` we can run tests for the adapter. Doing this automatically in Travis (like we already do it in our main precice project) would be great. 

An additional nice-to-have: In my testing environment I eliminate the dependency on preCICE by using the mock module. This also allows running the tests without preCICE being installed on the system. Therefore, we can test on different configurations, such as:

- [x] Linux with preCICE (still needs to be added in `systemtests`)
- [x] Linux without preCICE (closed by #27)
- [x] MacOS (closed by #27)
- [x] Windows (which I sometimes use for test-driven development of this adapter, closed by #27)

**Comment by shkodm** [comment]
I would work on it

**Comment by BenjaminRueth** [comment]
I just updated the description of this issue based on the outcome of #27. What remains to be done: proper system tests using the real (not the mocked) preCICE.

**Comment by BenjaminRueth** [comment]
Several test cases for the FEniCS adapter are provided in https://github.com/precice/systemtests.
